
import {Providers} from "./providers";
import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
      <html lang="en" className='light m-4'>
      {/*b站图片显示meta*/}
      <meta name="referrer" content="no-referrer"/>
      <body className={inter.className}>
      <Providers>
        {children}
      </Providers>
      </body>
      </html>
  );
}